name: GitHub to Telegram
on: [push, pull_request]

jobs:
  send-to-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send Telegram Notification
        run: |
          chmod +x .github/scripts/send.sh
          .github/scripts/send.sh
        env:
          TELEGRAM_TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}